spring:
  data:
    mongodb:
      uri: mongodb://cybodelic:Download1#@cluster0-shard-00-00-mjfgm.mongodb.net:27017,cluster0-shard-00-01-mjfgm.mongodb.net:27017,cluster0-shard-00-02-mjfgm.mongodb.net:27017/<DATABASE>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin